version: '2'
services:
    # The ERP Container
    # -----------------
    # Accessing container via ssh:
    # ssh in den Container:   ssh localhost -l s3 -p 2205 -i docker_erp.key
    #
    erp-bpmn:
      image: abas/pi-erp:latest
      container_name: "essentials_erp"

      ports:
      - "2205:22"
      - "8001:80"
      - "6560:6550"
      - "48592:48392"

      environment:
      - ABAS_HOST
      - ABAS_GUI_PORT=48592

      # starteVersion muss wegen der Volltextsuche als User s3 gestartet werden
      # Als root-user gibt es sonst Probleme wegen dem ulimit der open files.
      user: s3
      hostname: dockerbau

    # nexus host for madep
    nexus:
      image: sonatype/nexus:oss
      container_name: "essentials_nexus"
      ports:
      - "8081:8081"
