..!interpreter english translate noabbrev         
..*****************************************************************************
.. FOP-Name :		VARNAMELIST.YVARTAB.FX
.. Date : 			10.09.2014
.. Author : 		bf
.. Resposible : 	bf
.. Superviser : 		bf
.. Copyright : (c)  2014
.. Function : 
..*****************************************************************************
.. Tabellenteil intitialisieren
.input "ow1/SUB.INIT.TABLE.SCREEN"
.. 
.continue